### ISSUE TITLE
Not python 2 compatible. 

### ISSUE THREAD

**Issue by mkuiack** [transientskp/pyse#1]
``` bash
from pip install radio-pyse

$ pyse --detection 5 --radius 400 --csv --force-beam * 
Processing 20160930093114UTC_S307.5_I16x1_W6_A1.5.fits (file 1 of 2719).
Thresholding with det = 5.000000 sigma, analysis = 3.000000 sigma
/scratch/mkuiack/venv2/local/lib/python2.7/site-packages/sourcefinder/image.py:761: RuntimeWarning: invalid value encountered in greater
  (self.data_bgsubbed > analysisthresholdmap) &
Traceback (most recent call last):
  File "/scratch/mkuiack/venv2/bin/pyse", line 396, in <module>
    print_(run_sourcefinder(files, options), end=' ')
  File "/scratch/mkuiack/venv2/bin/pyse", line 388, in run_sourcefinder
    csvfile.write(csv(sr))
  File "/scratch/mkuiack/venv2/bin/pyse", line 93, in csv
    file=output)
  File "/scratch/mkuiack/venv2/local/lib/python2.7/site-packages/six.py", line 782, in print_
    _print(*args, **kwargs)
TypeError: unicode argument expected, got 'str'
```

**Comment by mkuiack** [comment]
#2

**Comment by gijzelaerr** [comment]
solved.
