### ISSUE TITLE
v0.3.3 -> "sig" parameter not in measurements

### ISSUE THREAD

**Issue by tmillenaar** [transientskp/pyse#109]
Hey guys,

I have been trying out the new release v0.3.3, thanks again for the effort you guys put into this!

I did notice a bug when running with `image.VECTORIZED = True`. It seems to stem from the change made in this commit:
https://github.com/transientskp/pyse/commit/7529c36037a4854ece718b8edf34abcf161a9f16
Here you change the sig parameter from `__setattr__` to `__setitem__`.

Since now the `__setitem__` is triggered, we arrive here: https://github.com/transientskp/pyse/blob/b662f48cd116317de0469581eaea405bc80ef6ac/sourcefinder/extract.py#L283 and find that 'sig' is not in `self.measurements` and we get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/timo/software/astron/pyse/sourcefinder/image.py", line 35, in timed
    result = method(*args, **kw)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/timo/software/astron/pyse/sourcefinder/image.py", line 541, in extract
    return self._pyse(
           ^^^^^^^^^^^
  File "/home/timo/software/astron/pyse/sourcefinder/image.py", line 1323, in _pyse
    param["sig"] = maxis[count] / self.rmsmap.data[tuple(maxposs[count])]
    ~~~~~^^^^^^^
  File "/home/timo/software/astron/pyse/sourcefinder/extract.py", line 289, in __setitem__
    raise AttributeError("Invalid parameter")
AttributeError: Invalid parameter

```
To reproduce this, you could run the following from the root of the repository:

```python
from sourcefinder.accessors import open as pyse_open
from sourcefinder.accessors import sourcefinder_image_from_accessor
from sourcefinder import image
image.VECTORIZED = True
path = "test/data/NCP_sample_image_1.fits"
fits_im = pyse_open(path)
pyse_im = sourcefinder_image_from_accessor(fits_im)
pyse_im.extract(8,8)
```

I imagine the fix would either be to add 'sig' to self.measurements or to revert the change.

Either way, I wish you guys a merry christmas and a happy new year!

Cheers,
Timo

**Comment by HannoSpreeuw** [comment]
Thanks, I encountered this before. 

I think [commit 7529c36](https://github.com/transientskp/pyse/commit/7529c36037a4854ece718b8edf34abcf161a9f16) was issued to fix #82 

So if I revert that commit, 
```
hatch run lint:mypy --install-types --non-interactive --pretty 
```
will not pass - can you check? - and I will have to fix #82 in a different way.

Anyway, that line 
```
param["sig"] = maxis[count] / self.rmsmap.data[tuple(maxposs[count])]
```
is part of the `reconvert operation` discussed in issue #90 - needed because the unit test adhere to the old, i.e. current, format of collecting source parameters - and will be replaced.

Or removed, if we choose to adapt the unit tests to the new RAM-aligned format.

After contemplation adapting the unit tests to the new RAM-aligned format may have my preference.

**Comment by HannoSpreeuw** [comment]
For now, if you run with VECTORIZED=True, comment out the [reconvert operation to pass the unit tests, i.e. lines 1319-1347](https://github.com/transientskp/pyse/blob/b662f48cd116317de0469581eaea405bc80ef6ac/sourcefinder/image.py#L1319).

**Comment by tmillenaar** [comment]
"can you check?" -> yes it also fails for me on `param.sig` if I run that hatch command.

I am all for adapting tests to the new RAM-aligned format of course.
For now I will pin the dependency to v0.3.2. The suggestion to comment those lines works locally of course but my CI does not pass otherwise.

**Comment by HannoSpreeuw** [comment]
> The suggestion to comment those lines works locally of course but my CI does not pass otherwise.
Yes, that makes sense.

We will tackle this next month.

Enjoy your holidays!

**Comment by HannoSpreeuw** [comment]
> "can you check?" -> yes it also fails for me on `param.sig` if I run that hatch command.

After some contemplation, I think that **mypy** is wrong in this case, it somehow does not see that we are dealing with a [extract.ParamSet](https://github.com/transientskp/pyse/blob/8bd77c9ae181ade28a0f78ceeed02fe25e90ccd6/sourcefinder/extract.py#L228) instantiation i.e. a [collections.abc.MutableMapping.](https://docs.python.org/3/library/collections.abc.html#collections.abc.MutableMapping). 

So that line [1285](https://github.com/transientskp/pyse/blob/8bd77c9ae181ade28a0f78ceeed02fe25e90ccd6/sourcefinder/image.py#L1285C17-L1285C86):
```
                param["sig"] = maxis[count] / self.rmsmap.data[tuple(maxposs[count])]
```
Should in fact be
```
                param.sig = maxis[count] / self.rmsmap.data[tuple(maxposs[count])]
```
which is the current way that vectorized code should mimick its non-vectorized counterpart in [line 224 from the extract module](https://github.com/transientskp/pyse/blob/8bd77c9ae181ade28a0f78ceeed02fe25e90ccd6/sourcefinder/extract.py#L224):
```
        measurement.sig = self.sig()
```
with _measurement_ being a _extract.ParamSet_ instance. 
Oddly enough, **mypy** does not complain about this line.

@suvayu Do you agree with this line of reasoning and do you think we can slightly alter 
`hatch run lint:mypy --install-types --non-interactive --pretty` as part of our CI such that it will not raise
```
sourcefinder/image.py:1285: error: "ParamSet" has no attribute "sig"  [attr-defined]
```
?

**Comment by suvayu** [comment]
I'm not sure I agree. The way I see this is that `ParamSet` defines a bunch of keys, but in other places (during use, not inside the definition) it sets the `.sig` attribute.  So you end up with different instances of `ParamSet` sometimes having the `.sig` attribute and sometimes not having it.  You can check this by calling `my_paramset_instance.keys()`, my guess is it will not include `'sig'`.  This is inconsistent (i.e. dynamically adding attributes), which is why `mypy` complains.

I see two possible *correct* implementations for `ParamSet`
1. no keys are specified, everything is dynamic, which would actually be my initial guess given the class name. in this case the implementation should check if a key exists and handle when it doesn't
2. a fixed set of keys, nothing added dynamically, and in cases where certain keys don't make sense, they have "invalid" values like `None` or `NaN`.

**Comment by HannoSpreeuw** [comment]
Allright, that feels like a pretty clear explanation.

But then adding a line 
```
        self.sig = None
```
to the `ParamSet` class  `__init__`, together with that line 1285 in the image module
```
                param.sig = maxis[count] / self.rmsmap.data[tuple(maxposs[count])]
```
would suffice, right?
This should be your option 2, I guess.

If this really that simple, I apologize for all the fuss and I will fix it.

**Comment by suvayu** [comment]
I'm not sure that would be completely correct, because it continues to mix
keys with attributes, although it might fix the mypy error.

I think it should be included in the measurements dict that's defined
inside `ParamSet`. I'm, of course, naively assuming `sig` is in no way
special than the other params.

-- 
Suvayu

Open source is the future. It sets us free.

**Comment by HannoSpreeuw** [comment]
Yeah, at [ParamSet instantiation](https://github.com/transientskp/pyse/blob/8bd77c9ae181ade28a0f78ceeed02fe25e90ccd6/sourcefinder/extract.py#L234) both attributes as floats and booleans as well as dicts are initialised.

I guess I will not try to reengineer that as part of this issue.
