### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by dentalfloss1** [transientskp/pyse#35]
I ran into the error below when trying to run pyse -h installed from the main branch. I believe this link should provide a straightforward solution: https://stackoverflow.com/questions/70870041/cannot-import-name-mutablemapping-from-collections
```
Traceback (most recent call last):
  File "/mnt/Gunther/Software/pysenv/bin/pyse", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/mnt/Gunther/Software/pyse/scripts/pyse", line 32, in <module>
    from sourcefinder.accessors import open as open_accessor
  File "/mnt/Gunther/Software/pyse/sourcefinder/accessors/__init__.py", line 16, in <module>
    from sourcefinder.image import ImageData
  File "/mnt/Gunther/Software/pyse/sourcefinder/image.py", line 11, in <module>
    from sourcefinder import extract
  File "/mnt/Gunther/Software/pyse/sourcefinder/extract.py", line 8, in <module>
    from collections import MutableMapping
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

**Comment by HannoSpreeuw** [comment]
In which way did you install pyse?
