### ISSUE TITLE
TypeError: 'tuple' object does not support item assignment

### ISSUE THREAD

**Issue by tmillenaar** [transientskp/pyse#91]
Hey both :)

I encountered an error that I think has a simple fix.

If the following line is triggered:

https://github.com/transientskp/pyse/blob/c8e2bd2078114e48ce7c1f2bec122924386d6289/sourcefinder/extract.py#L336

An error is raised:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/pdb.py", line 1723, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python3.10/pdb.py", line 1583, in _runscript
    self.run(statement)
  File "/usr/lib/python3.10/bdb.py", line 598, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/millenaar/software/astron/trap/trap/run.py", line 58, in <module>
    null_detection_fluxes = force_fit(pyse_im, positions=null_detection_coords)
  File "/home/millenaar/software/astron/trap/trap/source_extraction.py", line 216, in force_fit
    forced_fits = pyse_im.fit_fixed_positions(positions, boxsize)
  File "/home/millenaar/software/astron/trap/venv/lib/python3.10/site-packages/sourcefinder/image.py", line 784, in fit_fixed_positions
    fit_results = self.fit_to_point(x, y,
  File "/home/millenaar/software/astron/trap/venv/lib/python3.10/site-packages/sourcefinder/image.py", line 713, in fit_to_point
    measurement, _, _ = extract.source_profile_and_errors(
  File "/home/millenaar/software/astron/trap/venv/lib/python3.10/site-packages/sourcefinder/extract.py", line 807, in source_profile_and_errors
    param.compute_bounds(data.shape)
  File "/home/millenaar/software/astron/trap/venv/lib/python3.10/site-packages/sourcefinder/extract.py", line 336, in compute_bounds
    self.bounds["peak"][0] = self.bounds["peak"][1]
TypeError: 'tuple' object does not support item assignment
```

In my case, self.bounds looks like so: `{'peak': (-0.008640664629638195, -0.025921993888914585, False)}`.
Here 'peak' is a tuple, and the line I linked above is trying to set `self.bounds["peak"][0]`. Since 'peak' is a tuple we cannot set this.
The tuple in question is defined a few lines above:
Here:
https://github.com/transientskp/pyse/blob/c8e2bd2078114e48ce7c1f2bec122924386d6289/sourcefinder/extract.py#L323
And here:
https://github.com/transientskp/pyse/blob/c8e2bd2078114e48ce7c1f2bec122924386d6289/sourcefinder/extract.py#L326

I think the simplest solution is to use a list instead of  a tuple. If you do want a tuple, we will have to reconstruct the tuple as a whole, like so for example: `self.bounds["peak"] = (self.bounds["peak"][1], *self.bounds["peak"][1:])`.

Let me know if I can be of any further assistance in this.

Cheers,
Timo

P.S.: I ran on python 3.10

**Comment by HannoSpreeuw** [comment]
First of all, I am very much interested in the settings (image and applied PySE parameters) that got you into this:
Does this actually occur for the intended situation, i.e. a negative peak spectral brightness? In that case 1.5 * negative is smaller than 0.5 * negative while our fitting routine, i.e. [scipy.optimize.least_squares](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.least_squares.html) demands that the upper bound is larger (in this case less negative) than the lower bound. That is why these two bounds are switched for a negative peak spectral brightness.

Are you processing an image not in Stokes I? I.e. Stokes U, Q, V or a linear polarization product XX, YY, XY or YX?

A negative peak spectral brightness is not possible for an island of pixels detected in a Stokes I image unless there is something wrong with the rms noise map, i.e. the map that shows the standard deviation of the background pixel values across the image. A standard deviation should alsways be positive. In PySE this array is `image.ImageData.rmsmap`. It should have zero negative values for a Stokes I image. Could you please verify that, if you are indeed processing a Stokes I image? 
See [this similar remark](https://github.com/transientskp/pyse/issues/72#issuecomment-2309735838) as part of a different issue.

_In any case, this tuple item assignment issue should be fixed , I will take care of it, most likely in the way you proposed._

Oddly enough, the [testReverseSE unit test](https://github.com/transientskp/pyse/blob/c8e2bd2078114e48ce7c1f2bec122924386d6289/test/test_image.py#L451) did not catch it. I will look into that as well.

**Comment by tmillenaar** [comment]
Thanks for taking a look :)

I imagine indeed this does not occur for the regular intended situation. I got this error by force fitting a location.
In the first image I found a source and then for some subsequent images I wanted to force fit that same location to keep the light-curve going even though the source was not found by PySE. At the bottom I posted two images to show what this looks like.

If you want to reproduce this, you can use some test images I use that can be found here:
https://git.astron.nl/RD/trap_test_data

I will put some code here that assumes you checked out that repo locally and have pyse installed.
Then you can run the following code:

```Python
from sourcefinder.accessors import open as pyse_open
from sourcefinder.accessors import sourcefinder_image_from_accessor

im_path = "lofar1/GRB201006A_final_2min_srcs-t0002-image-pb.fits"

im = pyse_open(im_path)
sourcefinder_image = sourcefinder_image_from_accessor(im, back_size_x=50, back_size_y=50)

sample_coord = [[61.42263448, 63.33334492]]

sourcefinder_image.fit_fixed_positions(sample_coord, 32.468749293298835)
```

This errors for me with the error posted in the original post.
Note that for the error to occur here I need to set back_size_x=50 and back_size_y=50. If I use the defaults the code does run.
I imagine this is circumstantial, but wanted to mention it in case it does turn out to be relevant for you.

The images for reference:

Image lofar1/GRB201006A_final_2min_srcs-t0000-image-pb.fits: 
![image](https://github.com/user-attachments/assets/1a223ef8-7309-4db3-b1b2-833f12b81465)

Image lofar1/GRB201006A_final_2min_srcs-t0002-image-pb.fits:
![image](https://github.com/user-attachments/assets/47334824-17b0-4234-8e29-aad70e6b930e)

**Comment by HannoSpreeuw** [comment]
Ah yes, I overlooked fixed-position fitting. In that case you can indeed find a negative peak spectral brightness.

And it makes sense that [testReverseSE](https://github.com/transientskp/pyse/blob/c8e2bd2078114e48ce7c1f2bec122924386d6289/test/test_image.py#L451) did not catch this error, since that is a totally different kind of test. 
Closer to what you have been doing are the tests within the [TestFitFixedPositions class](https://github.com/transientskp/pyse/blob/c8e2bd2078114e48ce7c1f2bec122924386d6289/test/test_image.py#L64C7-L64C28), but apparently these fixed positions do not correspond to negative pixel values, since they all pass.

Thanks for sharing all that setup info. Beautiful.
Seems great to add your setup (including your image) as a unit test for fixed-position fitting on negative pixel values.
I will do so.

**Comment by tmillenaar** [comment]
Just a note if you do intent on using the test image, be mindful that it is 65MB. Since git stores a copy of all files for every commit it might not be very pleasant to have a file of such a size in the repo. This is why I created the separate test repo. I use that as a submodule hence that data is not copied on every commit. That is just to say you might not just want to add that image to your test data sets

**Comment by HannoSpreeuw** [comment]
` git stores a copy of all files for every commit`
Wow. That is truly inefficient. 

Good point, I see that we have images of half that size in `test/data`, one of which seems redundant. 
So I might be able to get away with adding just one of your three images while removing that one.

The thing is, I have worked with these [trap-test-data](https://github.com/transientskp/trap-test-data) before, i.e. as part of TraP, and I always get confused and mess things up. Since then I try to stay away from submodules, it is an extra abstraction level that I tend to forget.

Btw, according to [the docs](https://tkp.readthedocs.io/en/latest/devref/procedures/testing.html#test-data) the [trap-test-data](https://github.com/transientskp/trap-test-data)  are still used, right?

**Comment by HannoSpreeuw** [comment]
Btw, Git LFS also did not provide a solution, since [we kept running out of LFS quota](https://github.com/transientskp/pyse/pull/22#issue-952138751).

**Comment by tmillenaar** [comment]
Correct, TraP is still using trap-test-data.

I am now experimenting with a new repo here: https://git.astron.nl/RD/trap

But that is not near ready for use by others. There I use the test data I referred to in the previous comment. It is a mere subset of trap-test-data for the original tkp repo. I might wat to use more or even all of that test data later on but we'll see when we get there. For now I am just experimenting with those few images.

**Comment by HannoSpreeuw** [comment]
I will cut out the relevant part of your image, following this [SO link](https://stackoverflow.com/questions/32728218/cropping-very-large-fits-files-using-specified-boundaries?rq=3) and Astropy's [Cutout2D class](https://docs.astropy.org/en/latest/api/astropy.nddata.utils.Cutout2D.html).

That should make it  easy to decrease the image size from 64 MB to well below 10 MB.

**Comment by HannoSpreeuw** [comment]
I can reproduce your error.
